apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: zayed17/ecommerce:latest
        ports:
        - containerPort: 3009